on:
  pull_request:
    branches:
      - main

jobs:
  wilco:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Pr checks

    steps:
      - name: Check out project
        uses: actions/checkout@v2

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Wilco checks
        id: Wilco
        uses: trywilco/actions@main
        with:
          engine: ${{ secrets.WILCO_ENGINE_URL }}
  # Congrats on your new README file! 
  ![Alt text](https://i.giphy.com/L0O3TQpp0WnSXmxV8p.gif)
  # [Let's go!](https://app.wilco.gg/chat/lucca)
